### ISSUE TITLE
Game crashes on console/BSNES when defeating enemies sometimes

### ISSUE THREAD

**Issue by abyssonym** [abyssonym/sai2_rando#6]

**Comment by abyssonym** [comment]
It seems this bug is caused by the "no random encounters" patch.

**Comment by jet082** [comment]
Ah yeah, I intended to list this as an issue since it was noticed in the community awhile back, but since it only happens on bsnes (and maybe on real hardware?), I didn't want to bother you with it.

But I can confirm it does this in bizhawk using the bsnes core as well. I also believe that it happens randomly, even sometimes without defeating enemies.

**Comment by abyssonym** [comment]
This is fixed in v3.
