### ISSUE TITLE
Quick Magic Switch can select Cure when you don't have it

### ISSUE THREAD

**Issue by ianestrachan** [abyssonym/sai2_rando#9]
I gave the quick magic switch a try and I noticed that with only 2 magic bottles, the L and R buttons would toggle between Feather, Recovery, and Cure (the level 8 magic). Nothing happens if you attempt to cast it, since you don't have enough magic, so this is a fairly harmless bug.

Then I picked up a third magic bottle, and it did not include Tie in the rotation, as it should have.

Reproduction steps:
- Enable Quick Magic Switch
- Get the wand and a minimal number of magic bottles and use L & R, the spells are not right.

**Comment by ianestrachan** [comment]
Also, if you select Cure when you don't have it unlocked, and then go into the Magic menu, very `!!FUN!!` things happen involving the screen getting covered in garbage (at least in BSNES), so it's a lot more... interesting... than the soft lock in #8.

**Comment by abyssonym** [comment]
Fixed in 0da5fa31bf23b11240f476a979a4b84257a7f71d.
- The fast magic patch had been checking 16-bit values instead of 8-bit values, so if Shove was learned, which occupies the byte after Cure, then the game would think that Cure was learned. It now correctly checks the 8-bit value.
- Previously, the magic swap did not populate the spell list on its own. You had to check the magic menu before the new spells would become available. It now populates the spell list every time L or R is pressed.
